### ISSUE TITLE
so -R is...  err, two things?

### ISSUE THREAD

**Issue by altendky** [Julian/venvs#57]
https://github.com/Julian/venvs/blob/a14e1efc273f288c66725fede1668f9de81ce55c/venvs/make.py#L24
https://github.com/Julian/venvs/blob/a14e1efc273f288c66725fede1668f9de81ce55c/venvs/make.py#L50-L54

https://github.com/Julian/venvs/blob/a14e1efc273f288c66725fede1668f9de81ce55c/venvs/common.py#L141-L146

This also seems like not great functionality for Click.

https://repl.it/@altendky/PastelAntiqueAccess-1
```python3
import click
import click.testing


@click.command()
@click.option('-R', 'first')
@click.option('-R', 'second')
def main(first, second):
    pass


def click_runner(command):
    print(command.name)
    runner = click.testing.CliRunner()
    result = runner.invoke(
        command,
        [],
        catch_exceptions=False,
    )
    print(result.output)

click_runner(main)
```
Output is...  whatever.  There's no exception or warning or...

**Comment by Julian** [comment]
Nice :/...

That seems pretty undesirable.

But yeah I guess one needs renaming, though if #29 ever happens we can keep both...

**Comment by altendky** [comment]
I would think we could just drop `-R` for root for now.

**Comment by Julian** [comment]
I *think* the reason I had that was click otherwise won't let you pass in a
different root (e.g. in tests).

**Comment by altendky** [comment]
I think root yes.  But couldn't we pass it via `--root`?

**Comment by Julian** [comment]
Sounds reasonable

**Comment by altendky** [comment]
Turns out we pass it by the name `locator`.

https://github.com/Julian/venvs/blob/a14e1efc273f288c66725fede1668f9de81ce55c/venvs/tests/utils.py#L79-L89
