### ISSUE TITLE
The name...

### ISSUE THREAD

**Issue by altendky** [Julian/venvs#61]
`venvs` as a name has some issues.  We don't use `venv` and `venvs` must be explicitly distinguished in conversation from the plural of the things that `venv` (or `virtualenv`) creates.  A couple weeks ago I thought through some alternatives but almost all were taken on PyPI, albeit some by 'dead' projects.  One was not.  Just thought I'd toss it out there and have a place to put future ideas.

* `glen`
  * `GL`obal `EN`vironments
* `denver`
* `envelope`

(some commented in passing in `#python`)

**Comment by energizerhub** [comment]
- pysolate
- venvy

**Comment by Julian** [comment]
I am bad, I think the name is staying, sorry :C

Chalk another thing up confusing names in the ecosystem.
