### ISSUE TITLE
Intermittent build failures on cpy3.5, proooobably because tomlkit isn't preserving order when loading files

### ISSUE THREAD

**Issue by Julian** [Julian/venvs#74]

**Comment by altendky** [comment]
What, I have to go fix this in another TOML library for you?  :]

avakar/pytoml#39

**Comment by Julian** [comment]
Hahhhhhhh oy.

This one came from @energizerhub :) I don't remember why we had to switch even because it took me a year to merge his PR but seems at least likely that this is why based on the symptoms, since 3.5 didn't have ordered dicts on cpython.

**Comment by altendky** [comment]
https://github.com/sdispater/tomlkit/blob/cad4e0a8aebe000d7009f103986d0f1b2dec7347/tomlkit/container.py#L26

Awesome... Inheriting from `dict`.

**Comment by Julian** [comment]
The easiest solution was just dropping support for 3.5, hooray.
