### ISSUE TITLE
'Remove' AppVeyor build to avoid noisy build failures

### ISSUE THREAD

**Issue by altendky** [Julian/venvs#89]
In my repo I can go to `Settings` then `Webhooks` and I see an entry for AppVeyor.  I suspect deleting this will stop triggering the builds on AppVeyor thus avoiding future build failures caused by AppVeyor.

**Comment by altendky** [comment]
Or maybe I'm confused and this was already done since the last master build...

**Comment by Julian** [comment]
Hm, interesting -- I'm not getting failure emails, but well, regardless, removed the webhooks, lemme know if you see anything funky.
