### ISSUE TITLE
PR fails to upload coverage data

### ISSUE THREAD

**Issue by altendky** [Julian/venvs#90]
Maybe make the repository upload token available for PRs?

https://github.com/Julian/venvs/pull/48/checks?check_run_id=365463489#step:6:363
```
Error: Missing repository upload token
```

**Comment by Julian** [comment]
Hummm let's see how you do that...

**Comment by Julian** [comment]
Yeah I have no idea how to make this work I see nothing that'd let you do that, wat :/

**Comment by altendky** [comment]
How is it set up now?  As an environment variable?  Not at all because of codecov integration with github?

So there is https://github.com/codecov/codecov-action but sure, I would rather do CI agnostic activities with CI agnostic code.

**Comment by Julian** [comment]
It's currently just using the `codecov` executable directly, because of yeah your second point, but I don't think it matters much, the issue is just whether GHA supports sharing secrets with PRs (without say, letting them change the workflow code to be able to steal them).

Even if I were using the "official" codecov-action GHA I think you'd have the same issue.

**Comment by Julian** [comment]
Yeah it looks like that's the case, and that obviously this is already a known issue:

https://github.com/codecov/codecov-action/issues/29

and

https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/30678/highlight/true#M508

Fun.

**Comment by Julian** [comment]
Sigh, I guess for now just disabling running coverage for PRs.

**Comment by altendky** [comment]
Trio anyways decided that submitting code coverage results was an unlikely attack vector with minimal damage and just made the code public. Granted that's assuming everything else in the security chain works...

**Comment by Julian** [comment]
The token you mean? Yeah I probably agree with that especially considering
I never even look at codecov.io, sounds reasonable to me.
