### ISSUE TITLE
Getting installed.toml with [ [ "t", "w", "i", ......

### ISSUE THREAD

**Issue by altendky** [Julian/venvs#92]
Can you guess what it ought to be?  (PR to follow at least for a test for this)  I tried to recreate but even when I make a `dict` that's `==` to the config to be dumped...  `toml.dumps()` messes up the venvs-created dict and not my manually created dict.

```
install = [ [ "t", "w", "i", "n", "e",],]
requirements = []
link = [ [ "t", "w", "i", "n", "e",],]
link-module = []
python = "/home/altendky/repos/venvs/venv/bin/python"
"sys.version" = "Python 3.8.0\n"
```

**Comment by altendky** [comment]
So far every time I've set a breakpoint at the end of the snippet below I've seen the issue in the result of `toml.dumps(config)`.

https://github.com/Julian/venvs/blob/5643867e9ad0f25390ad1aaf1f18a23f361deda7/venvs/converge.py#L53-L63

I don't know why my PyCharm console isn't working but...  here's an image at least of my confused 'equal but dump differently' dicts.

![image](https://user-images.githubusercontent.com/543719/71534576-cb27a080-28cd-11ea-85e2-3333d0da3da9.png)

**Comment by Julian** [comment]
After 1ddb188e5bf0eae33ea9a527f6e699e758bd87db the code handling reading/writing this file basically has to be rewritten.

Certainly good to know though if it has a bug already.

**Comment by Julian** [comment]
OK, I made the change to JSON on master (and will release in a second), so give this another shot and lemme know.
